n = input('Degite Algo ')
print('O valor é decimal:', n.isdecimal())
print('O valor é alfanumérico:', n.isalnum())
print('O valor é numérico:', n.isnumeric())
print('O valor contêm espaços:', n.isspace())
print('O valor é um dígito:', n.isdigit())
print('O valor da tabela ASCII:', n.isascii())
print('O valor é um print:', n.isprintable())
print('O valor só contêm minúsculos', n.islower())
print('O valor é identificador:', n.isidentifier())
print('O valor é um título:', n.istitle())